#!/bin/sh
#
# makesrcdist - make a source distribution of codedoc.
#

if test $# != 1; then
	echo "Usage: ./makesrcdist version"
	exit 1
fi

version=$1

echo Creating tag for release...
git tag -m "Tag $version" v$version
git push origin v$version

echo Creating codedoc-$version.tar.gz...
git archive --format tar --prefix=codedoc-$version/ HEAD | gzip -v9 >codedoc-$version.tar.gz
gpg --detach-sign codedoc-$version.tar.gz
