name: codedoc
base: core22
version: "3.7"
summary: Code documentation utility.
description: |
  Codedoc is a documentation generator that scans the specified C and C++ source
  files to produce an XML representation of globally accessible classes,
  constants, enumerations, functions, structures, typedefs, unions, and
  variables - the XML file is updated as necessary.

confinement: strict

grade: stable

icon: codedoc-128.png

architectures:
  - build-on: amd64
  - build-on: arm64
  - build-on: armhf

apps:
    codedoc:
        command: bin/codedoc
        plugs: [home]

parts:
    mxml:
        plugin: autotools
        autotools-configure-parameters: [--disable-shared --prefix=/]
        source-type: git
        source: https://github.com/michaelrsweet/mxml.git

    main:
        plugin: autotools
        autotools-configure-parameters: [--prefix=/]
        source: .
        after: [mxml]
        build-packages: [zlib1g-dev, pkg-config]
